# Generated by Django 5.0.4 on 2024-04-06 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_holiday_slot_remove_calender_i_attendance_periods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='periods',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
