# Generated by Django 5.0.4 on 2024-04-06 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_attendance_periods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='periods',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
