# Generated by Django 5.0.4 on 2024-04-13 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_attendance_periods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calender',
            old_name='dates',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='periods_id',
            new_name='period_id',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='periods',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='leave',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('class_id', 'course_id', 'day', 'period_id')},
        ),
    ]
